name: Update GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *' # This will run daily at midnight
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub Pages repository
      uses: actions/checkout@v3
      with:
        repository: RocketGod-git/RocketGod-git.github.io
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout main repository
      uses: actions/checkout@v3
      with:
        repository: RocketGod-git/RocketGod-git
        path: main_repo

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert README.md to HTML
      run: |
        pandoc main_repo/README.md -o index.html

    - name: Debug - List Files
      run: |
        ls -la
        ls -la main_repo

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.html
        git commit -m 'Update index.html from README.md' || echo "No changes to commit"
        git push
